"""
Character Lock Agent - Second agent in the pipeline
Ensures character consistency across all scenes
"""
import os
import json
from typing import List, Dict, Any
from anthropic import Anthropic
from studio.schemas import SceneClip, CharacterSpec, ProductionJob


class CharacterLockAgent:
    """
    Analyzes script and locks down character appearances
    Creates reference specifications for consistent generation
    """

    def __init__(self):
        api_key = os.environ.get('ANTHROPIC_API_KEY')
        if not api_key:
            print("⚠️  ANTHROPIC_API_KEY not set - Character Lock Agent will skip")
            self.client = None
        else:
            self.client = Anthropic(api_key=api_key)
        self.model = "claude-sonnet-4-5"

    async def lock_characters(self, job: ProductionJob, clips: List[SceneClip]) -> ProductionJob:
        """
        Analyze all scenes and create locked character specifications

        Args:
            job: ProductionJob
            clips: List of SceneClip objects with script data

        Returns:
            Updated ProductionJob with global_characters populated
            Updated clips with character assignments
        """
        print(f"🎭 Character Lock Agent: Analyzing characters...")

        # Skip if no API key
        if not self.client:
            print(f"   ⚠️  Skipping character analysis (add ANTHROPIC_API_KEY for character locking)")
            job.global_characters = []
            return job

        # Build combined scene descriptions
        scene_descriptions = []
        for clip in clips:
            scene_descriptions.append({
                "sequence": clip.sequence_number,
                "description": clip.scene_description,
                "narration": clip.narration_text
            })

        prompt = f"""You are a character design specialist. Analyze this video script and identify all recurring characters.

Video Title: {job.title}
Visual Style: {job.visual_style}
Tone: {job.tone}

Scenes:
{json.dumps(scene_descriptions, indent=2)}

For each recurring character (appears in multiple scenes OR is central to the story):
1. Create a detailed visual description that will ensure consistency
2. Include: age, gender, ethnicity, build, facial features, hair, clothing, distinctive features
3. Be specific enough that an artist could recreate them exactly

Return a JSON array of characters:
[
  {{
    "character_id": "unique_id",
    "name": "Character Name",
    "visual_description": "Extremely detailed visual description (200+ words)",
    "appearance_notes": "Key consistency points",
    "appears_in_scenes": [1, 2, 5]
  }},
  ...
]

If there are no recurring characters (abstract/nature content), return an empty array.
"""

        response = self.client.messages.create(
            model=self.model,
            max_tokens=3000,
            messages=[{"role": "user", "content": prompt}]
        )

        # Parse characters
        response_text = response.content[0].text
        characters_data = self._parse_characters_response(response_text)

        # Create CharacterSpec objects
        global_characters = []
        for char_data in characters_data:
            char_spec = CharacterSpec(
                character_id=char_data.get('character_id', f"char_{len(global_characters) + 1}"),
                name=char_data['name'],
                visual_description=char_data['visual_description'],
                appearance_notes=char_data.get('appearance_notes', ''),
                reference_image_url=None,  # Will be generated by Frame Agent
                lora_model_id=None  # Could train LoRA for perfect consistency
            )
            global_characters.append(char_spec)

            # Assign to relevant clips
            appears_in = char_data.get('appears_in_scenes', [])
            for clip in clips:
                if clip.sequence_number in appears_in:
                    clip.characters.append(char_spec)

        job.global_characters = global_characters

        if global_characters:
            print(f"✅ Character Lock Agent: Locked {len(global_characters)} characters")
            for char in global_characters:
                print(f"   - {char.name}: {char.visual_description[:100]}...")
        else:
            print(f"✅ Character Lock Agent: No recurring characters (abstract content)")

        return job

    def _parse_characters_response(self, text: str) -> List[Dict[str, Any]]:
        """Parse LLM response into character data"""
        try:
            # Find JSON array in response
            start_idx = text.find('[')
            end_idx = text.rfind(']') + 1
            if start_idx != -1 and end_idx > start_idx:
                json_text = text[start_idx:end_idx]
                characters = json.loads(json_text)
                return characters if characters else []
        except Exception as e:
            print(f"⚠️  Failed to parse characters JSON: {e}")

        return []
