"""
Sound Engineer Agent - Intelligent audio design and mixing
Uses Claude to analyze script/lighting/composition
Uses ElevenLabs API for music and sound effects generation
"""
import os
import json
from typing import List, Dict, Any, Optional
from anthropic import Anthropic
from studio.schemas import SceneClip, ProductionJob


class AudioLayer:
    """Represents an audio element in the mix"""
    def __init__(
        self,
        layer_type: str,  # "narration", "music", "sfx", "ambient"
        audio_url: Optional[str],
        start_time: float,
        duration: float,
        volume: float,  # 0.0 to 1.0
        fade_in: float = 0.0,
        fade_out: float = 0.0,
        description: str = ""
    ):
        self.layer_type = layer_type
        self.audio_url = audio_url
        self.start_time = start_time
        self.duration = duration
        self.volume = volume
        self.fade_in = fade_in
        self.fade_out = fade_out
        self.description = description

    def to_dict(self):
        return {
            "layer_type": self.layer_type,
            "audio_url": self.audio_url,
            "start_time": self.start_time,
            "duration": self.duration,
            "volume": self.volume,
            "fade_in": self.fade_in,
            "fade_out": self.fade_out,
            "description": self.description
        }


class SoundEngineerAgent:
    """
    Professional sound engineer that:
    1. Uses Claude to analyze script, lighting, composition for audio needs
    2. Uses ElevenLabs API to generate:
       - Background music
       - Sound effects (SFX)
       - Ambient atmosphere
    3. Balances audio levels for clarity
    4. Creates smooth transitions and fades
    5. Expert in audio production principles
    """

    def __init__(self):
        # Claude for audio direction analysis
        api_key = os.environ.get('ANTHROPIC_API_KEY')
        if not api_key:
            raise ValueError("ANTHROPIC_API_KEY required for Sound Engineer Agent")
        self.client = Anthropic(api_key=api_key)
        self.model = "claude-sonnet-4-5"

        # ElevenLabs for audio generation
        self.elevenlabs_api_key = os.environ.get('ELEVENLABS_API_KEY')
        if not self.elevenlabs_api_key:
            print("⚠️  ELEVENLABS_API_KEY not set - Sound Engineer will use mock audio")

        self.use_mock = os.environ.get('STUDIO_MOCK_GENERATION', 'false').lower() == 'true'

    async def design_audio(
        self,
        job: ProductionJob,
        clips: List[SceneClip]
    ) -> Dict[str, Any]:
        """
        Main method: Design complete audio mix for video

        Args:
            job: ProductionJob with video context
            clips: List of SceneClip objects with narration

        Returns:
            Dict with audio_layers, mixing_notes, and specifications
        """
        print(f"🎵 Sound Engineer: Designing audio for '{job.title}'...")

        # Step 1: Analyze the script for audio needs
        print(f"   🎼 Analyzing script emotional journey...")
        audio_direction = await self._analyze_audio_needs(job, clips)

        # Step 2: Generate background music
        print(f"   🎹 Generating background music...")
        music_layer = await self._generate_background_music(job, audio_direction)

        # Step 3: Identify SFX moments
        print(f"   🔊 Identifying sound effect moments...")
        sfx_layers = await self._design_sound_effects(clips, audio_direction)

        # Step 4: Plan narration audio (already generated by Audio Agent, but we add specs)
        print(f"   🎙️  Planning narration audio levels...")
        narration_layers = self._plan_narration_layers(clips)

        # Step 5: Add ambient sounds if needed
        print(f"   🌊 Adding ambient atmosphere...")
        ambient_layers = await self._design_ambient_audio(job, audio_direction)

        # Step 6: Create final mix specifications
        print(f"   🎚️  Balancing audio mix...")
        all_layers = narration_layers + [music_layer] + sfx_layers + ambient_layers
        mix_specs = self._create_mix_specifications(all_layers, job)

        print(f"✅ Sound Engineer: Audio design complete - {len(all_layers)} layers")

        return {
            "audio_layers": [layer.to_dict() for layer in all_layers],
            "mix_specifications": mix_specs,
            "audio_direction": audio_direction,
            "total_layers": len(all_layers)
        }

    async def _analyze_audio_needs(
        self,
        job: ProductionJob,
        clips: List[SceneClip]
    ) -> Dict[str, Any]:
        """
        Analyze script to determine audio requirements
        Returns audio direction with mood, energy, style
        """
        if not self.client:
            return self._get_default_audio_direction(job)

        try:
            # Build script summary
            script_summary = "\n".join([
                f"Scene {clip.sequence_number} ({clip.duration}s): {clip.narration_text[:100]}... [Emotion: {clip.emotional_beat}]"
                for clip in clips
            ])

            prompt = f"""You are a professional sound designer. Analyze this video script and provide audio direction.

VIDEO INFO:
Title: {job.title}
Duration: {job.duration_target}s
Platform: {job.platform}
Tone: {job.tone}

SCRIPT BREAKDOWN:
{script_summary}

Provide audio direction:
1. Overall music mood (cinematic, upbeat, dramatic, calm, suspenseful, etc.)
2. Music energy level (1-10)
3. Key SFX moments (where sound effects would enhance the story)
4. Ambient sound needs (background atmosphere)
5. Music transition points
6. Volume balance (narration vs music vs effects)

Return JSON:
{{
    "music_mood": "description",
    "energy_level": 7,
    "genre": "cinematic/electronic/ambient/etc",
    "sfx_moments": [
        {{"scene": 1, "timing": 2.5, "effect": "whoosh", "reason": "why this helps"}},
        {{"scene": 2, "timing": 1.0, "effect": "impact", "reason": "emphasize point"}}
    ],
    "ambient_sound": "description or null",
    "music_transitions": [
        {{"at_second": 15, "transition": "build intensity"}}
    ],
    "volume_mix": {{
        "narration": 1.0,
        "music": 0.3,
        "sfx": 0.6,
        "ambient": 0.2
    }}
}}"""

            response = self.client.messages.create(
                model=self.model,
                max_tokens=2000,
                messages=[{"role": "user", "content": prompt}]
            )

            analysis_text = response.content[0].text

            # Extract JSON
            start_idx = analysis_text.find('{')
            end_idx = analysis_text.rfind('}') + 1
            if start_idx != -1 and end_idx > start_idx:
                audio_direction = json.loads(analysis_text[start_idx:end_idx])
                return audio_direction

        except Exception as e:
            print(f"   ⚠️  Audio analysis failed: {e}")

        return self._get_default_audio_direction(job)

    async def _generate_background_music(
        self,
        job: ProductionJob,
        audio_direction: Dict[str, Any]
    ) -> AudioLayer:
        """
        Generate background music using ElevenLabs Sound Generation API
        """
        music_mood = audio_direction.get('music_mood', 'cinematic')
        genre = audio_direction.get('genre', 'ambient')
        duration = job.duration_target

        print(f"   🎵 Generating {genre} music ({music_mood} mood, {duration}s)...")

        # Check if we should use real generation or mock
        if self.elevenlabs_api_key and not self.use_mock:
            try:
                # Use ElevenLabs Sound Generation API
                import requests

                response = requests.post(
                    "https://api.elevenlabs.io/v1/sound-generation",
                    headers={
                        "xi-api-key": self.elevenlabs_api_key,
                        "Content-Type": "application/json"
                    },
                    json={
                        "text": f"{music_mood} {genre} background music, cinematic atmosphere",
                        "duration_seconds": min(duration, 22),  # ElevenLabs max 22s
                        "prompt_influence": 0.3
                    }
                )

                if response.status_code == 200:
                    # Save audio to local file or get URL
                    audio_url = f"data:audio/mp3;base64,{response.content.decode('utf-8')}"
                    print(f"   ✅ Background music generated via ElevenLabs")

                    return AudioLayer(
                        layer_type="music",
                        audio_url=audio_url,
                        start_time=0,
                        duration=duration,
                        volume=audio_direction.get('volume_mix', {}).get('music', 0.3),
                        fade_in=2.0,
                        fade_out=2.0,
                        description=f"{genre} background music - {music_mood} mood (ElevenLabs)"
                    )
                else:
                    print(f"   ⚠️  ElevenLabs API error: {response.status_code}")

            except Exception as e:
                print(f"   ⚠️  Music generation failed: {e}, using placeholder")

        # Mock mode or fallback
        return AudioLayer(
            layer_type="music",
            audio_url="https://example.com/music/placeholder.mp3",
            start_time=0,
            duration=duration,
            volume=0.3,
            fade_in=2.0,
            fade_out=2.0,
            description=f"[MOCK] {genre} background music - {music_mood} mood"
        )

    async def _design_sound_effects(
        self,
        clips: List[SceneClip],
        audio_direction: Dict[str, Any]
    ) -> List[AudioLayer]:
        """
        Generate sound effects using ElevenLabs Sound Generation API
        """
        sfx_layers = []
        sfx_moments = audio_direction.get('sfx_moments', [])

        cumulative_time = 0
        for clip in clips:
            # Check if this scene has SFX
            for sfx in sfx_moments:
                if sfx.get('scene') == clip.sequence_number:
                    effect_type = sfx.get('effect', 'whoosh')
                    timing = sfx.get('timing', 0)
                    reason = sfx.get('reason', '')

                    # Generate SFX using ElevenLabs
                    sfx_url = await self._generate_sound_effect(effect_type, reason)

                    sfx_layers.append(AudioLayer(
                        layer_type="sfx",
                        audio_url=sfx_url,
                        start_time=cumulative_time + timing,
                        duration=0.5,  # Most SFX are short
                        volume=audio_direction.get('volume_mix', {}).get('sfx', 0.6),
                        description=f"{effect_type} - {reason}"
                    ))

            cumulative_time += clip.duration

        print(f"   ✅ Generated {len(sfx_layers)} sound effects via ElevenLabs")
        return sfx_layers

    async def _design_ambient_audio(
        self,
        job: ProductionJob,
        audio_direction: Dict[str, Any]
    ) -> List[AudioLayer]:
        """
        Add ambient background sounds if needed
        """
        ambient_sound = audio_direction.get('ambient_sound')

        if not ambient_sound or ambient_sound == "null":
            return []

        # Create ambient layer
        ambient_layer = AudioLayer(
            layer_type="ambient",
            audio_url="https://example.com/ambient/placeholder.mp3",
            start_time=0,
            duration=job.duration_target,
            volume=audio_direction.get('volume_mix', {}).get('ambient', 0.2),
            fade_in=3.0,
            fade_out=3.0,
            description=f"Ambient: {ambient_sound}"
        )

        print(f"   ✅ Added ambient atmosphere: {ambient_sound}")
        return [ambient_layer]

    def _plan_narration_layers(self, clips: List[SceneClip]) -> List[AudioLayer]:
        """
        Create audio layer specs for narration (already generated by Audio Agent)
        """
        narration_layers = []
        cumulative_time = 0

        for clip in clips:
            if clip.audio_url:  # If Audio Agent already generated narration
                narration_layers.append(AudioLayer(
                    layer_type="narration",
                    audio_url=clip.audio_url,
                    start_time=cumulative_time,
                    duration=clip.duration,
                    volume=1.0,  # Narration is always full volume
                    description=f"Narration for scene {clip.sequence_number}"
                ))

            cumulative_time += clip.duration

        return narration_layers

    def _create_mix_specifications(
        self,
        audio_layers: List[AudioLayer],
        job: ProductionJob
    ) -> Dict[str, Any]:
        """
        Create final mixing specifications for Assembly Agent
        """
        return {
            "total_duration": job.duration_target,
            "sample_rate": 48000,  # Professional standard
            "channels": 2,  # Stereo
            "bitrate": 192,  # kbps
            "format": "aac",
            "normalization": "peak",  # Peak normalization to -1dB
            "compression": {
                "enabled": True,
                "threshold": -20,  # dB
                "ratio": 3.0,
                "attack": 5,  # ms
                "release": 50  # ms
            },
            "eq": {
                "narration_boost": "+2dB at 3kHz",  # Clarity
                "music_roll_off": "-3dB at 8kHz"   # Don't compete with narration
            },
            "ducking": {
                "music_under_narration": -6,  # Lower music by 6dB when narration plays
                "auto_duck": True
            }
        }

    async def _generate_sound_effect(self, effect_type: str, reason: str) -> str:
        """
        Generate a sound effect using ElevenLabs API
        """
        if self.elevenlabs_api_key and not self.use_mock:
            try:
                import requests

                response = requests.post(
                    "https://api.elevenlabs.io/v1/sound-generation",
                    headers={
                        "xi-api-key": self.elevenlabs_api_key,
                        "Content-Type": "application/json"
                    },
                    json={
                        "text": f"{effect_type} sound effect, {reason}",
                        "duration_seconds": 1.0,
                        "prompt_influence": 0.5
                    }
                )

                if response.status_code == 200:
                    return f"data:audio/mp3;base64,{response.content.decode('utf-8')}"
                else:
                    print(f"   ⚠️  ElevenLabs SFX generation failed: {response.status_code}")

            except Exception as e:
                print(f"   ⚠️  SFX generation error: {e}")

        # Fallback
        return f"https://example.com/sfx/{effect_type}.mp3"

    def _get_default_audio_direction(self, job: ProductionJob) -> Dict[str, Any]:
        """Fallback audio direction when LLM not available"""
        return {
            "music_mood": "engaging",
            "energy_level": 6,
            "genre": "cinematic",
            "sfx_moments": [],
            "ambient_sound": None,
            "music_transitions": [],
            "volume_mix": {
                "narration": 1.0,
                "music": 0.3,
                "sfx": 0.6,
                "ambient": 0.2
            }
        }
