"""
Sound Engineer Agent - Intelligent audio design and mixing
Adds sound effects, background music, and audio enhancement
"""
import os
import json
from typing import List, Dict, Any, Optional
from anthropic import Anthropic
from studio.schemas import SceneClip, ProductionJob
from studio.providers.kieai_provider import KieAIProvider


class AudioLayer:
    """Represents an audio element in the mix"""
    def __init__(
        self,
        layer_type: str,  # "narration", "music", "sfx", "ambient"
        audio_url: Optional[str],
        start_time: float,
        duration: float,
        volume: float,  # 0.0 to 1.0
        fade_in: float = 0.0,
        fade_out: float = 0.0,
        description: str = ""
    ):
        self.layer_type = layer_type
        self.audio_url = audio_url
        self.start_time = start_time
        self.duration = duration
        self.volume = volume
        self.fade_in = fade_in
        self.fade_out = fade_out
        self.description = description

    def to_dict(self):
        return {
            "layer_type": self.layer_type,
            "audio_url": self.audio_url,
            "start_time": self.start_time,
            "duration": self.duration,
            "volume": self.volume,
            "fade_in": self.fade_in,
            "fade_out": self.fade_out,
            "description": self.description
        }


class SoundEngineerAgent:
    """
    Professional sound engineer that:
    - Analyzes script emotional beats for music selection
    - Identifies moments needing sound effects (SFX)
    - Generates background music with MusicGen
    - Sources professional SFX from libraries
    - Balances audio levels for clarity
    - Creates smooth transitions and fades
    - Enhances overall audio quality
    - Expert in audio production principles
    """

    def __init__(self):
        # LLM for audio direction analysis
        api_key = os.environ.get('ANTHROPIC_API_KEY')
        if not api_key:
            print("⚠️  ANTHROPIC_API_KEY not set - Sound Engineer will use basic mode")
            self.client = None
        else:
            self.client = Anthropic(api_key=api_key)
        self.model = "claude-sonnet-4-5"

        # Kie.ai for audio generation
        kieai_api_key = os.environ.get('KIEAI_API_KEY')
        self.use_mock = os.environ.get('STUDIO_MOCK_GENERATION', 'false').lower() == 'true'

        if kieai_api_key and not self.use_mock:
            self.kieai_provider = KieAIProvider(api_key=kieai_api_key)
        else:
            self.kieai_provider = None

        # Sound effects library (URL-based for now)
        self.sfx_library = self._load_sfx_library()

    async def design_audio(
        self,
        job: ProductionJob,
        clips: List[SceneClip]
    ) -> Dict[str, Any]:
        """
        Main method: Design complete audio mix for video

        Args:
            job: ProductionJob with video context
            clips: List of SceneClip objects with narration

        Returns:
            Dict with audio_layers, mixing_notes, and specifications
        """
        print(f"🎵 Sound Engineer: Designing audio for '{job.title}'...")

        # Step 1: Analyze the script for audio needs
        print(f"   🎼 Analyzing script emotional journey...")
        audio_direction = await self._analyze_audio_needs(job, clips)

        # Step 2: Generate background music
        print(f"   🎹 Generating background music...")
        music_layer = await self._generate_background_music(job, audio_direction)

        # Step 3: Identify SFX moments
        print(f"   🔊 Identifying sound effect moments...")
        sfx_layers = await self._design_sound_effects(clips, audio_direction)

        # Step 4: Plan narration audio (already generated by Audio Agent, but we add specs)
        print(f"   🎙️  Planning narration audio levels...")
        narration_layers = self._plan_narration_layers(clips)

        # Step 5: Add ambient sounds if needed
        print(f"   🌊 Adding ambient atmosphere...")
        ambient_layers = await self._design_ambient_audio(job, audio_direction)

        # Step 6: Create final mix specifications
        print(f"   🎚️  Balancing audio mix...")
        all_layers = narration_layers + [music_layer] + sfx_layers + ambient_layers
        mix_specs = self._create_mix_specifications(all_layers, job)

        print(f"✅ Sound Engineer: Audio design complete - {len(all_layers)} layers")

        return {
            "audio_layers": [layer.to_dict() for layer in all_layers],
            "mix_specifications": mix_specs,
            "audio_direction": audio_direction,
            "total_layers": len(all_layers)
        }

    async def _analyze_audio_needs(
        self,
        job: ProductionJob,
        clips: List[SceneClip]
    ) -> Dict[str, Any]:
        """
        Analyze script to determine audio requirements
        Returns audio direction with mood, energy, style
        """
        if not self.client:
            return self._get_default_audio_direction(job)

        try:
            # Build script summary
            script_summary = "\n".join([
                f"Scene {clip.sequence_number} ({clip.duration}s): {clip.narration_text[:100]}... [Emotion: {clip.emotional_beat}]"
                for clip in clips
            ])

            prompt = f"""You are a professional sound designer. Analyze this video script and provide audio direction.

VIDEO INFO:
Title: {job.title}
Duration: {job.duration_target}s
Platform: {job.platform}
Tone: {job.tone}

SCRIPT BREAKDOWN:
{script_summary}

Provide audio direction:
1. Overall music mood (cinematic, upbeat, dramatic, calm, suspenseful, etc.)
2. Music energy level (1-10)
3. Key SFX moments (where sound effects would enhance the story)
4. Ambient sound needs (background atmosphere)
5. Music transition points
6. Volume balance (narration vs music vs effects)

Return JSON:
{{
    "music_mood": "description",
    "energy_level": 7,
    "genre": "cinematic/electronic/ambient/etc",
    "sfx_moments": [
        {{"scene": 1, "timing": 2.5, "effect": "whoosh", "reason": "why this helps"}},
        {{"scene": 2, "timing": 1.0, "effect": "impact", "reason": "emphasize point"}}
    ],
    "ambient_sound": "description or null",
    "music_transitions": [
        {{"at_second": 15, "transition": "build intensity"}}
    ],
    "volume_mix": {{
        "narration": 1.0,
        "music": 0.3,
        "sfx": 0.6,
        "ambient": 0.2
    }}
}}"""

            response = self.client.messages.create(
                model=self.model,
                max_tokens=2000,
                messages=[{"role": "user", "content": prompt}]
            )

            analysis_text = response.content[0].text

            # Extract JSON
            start_idx = analysis_text.find('{')
            end_idx = analysis_text.rfind('}') + 1
            if start_idx != -1 and end_idx > start_idx:
                audio_direction = json.loads(analysis_text[start_idx:end_idx])
                return audio_direction

        except Exception as e:
            print(f"   ⚠️  Audio analysis failed: {e}")

        return self._get_default_audio_direction(job)

    async def _generate_background_music(
        self,
        job: ProductionJob,
        audio_direction: Dict[str, Any]
    ) -> AudioLayer:
        """
        Generate background music using MusicGen or similar
        """
        music_mood = audio_direction.get('music_mood', 'cinematic')
        genre = audio_direction.get('genre', 'ambient')
        duration = job.duration_target

        print(f"   🎵 Generating {genre} music ({music_mood} mood, {duration}s)...")

        # Check if we should use real generation or mock
        if self.kieai_provider and not self.use_mock:
            try:
                # Use MusicGen via kie.ai
                result = self.kieai_provider.call_any_model(
                    model_name="musicgen",
                    endpoint="/audio/generate-music",
                    payload={
                        "duration": min(duration, 30),  # MusicGen typically max 30s
                        "genre": genre,
                        "mood": music_mood,
                        "tempo": "medium"
                    }
                )

                audio_url = result.get("audio_url")

                print(f"   ✅ Background music generated")

                return AudioLayer(
                    layer_type="music",
                    audio_url=audio_url,
                    start_time=0,
                    duration=duration,
                    volume=audio_direction.get('volume_mix', {}).get('music', 0.3),
                    fade_in=2.0,
                    fade_out=2.0,
                    description=f"{genre} background music - {music_mood} mood"
                )

            except Exception as e:
                print(f"   ⚠️  Music generation failed: {e}, using placeholder")

        # Mock mode or fallback
        return AudioLayer(
            layer_type="music",
            audio_url="https://example.com/music/placeholder.mp3",
            start_time=0,
            duration=duration,
            volume=0.3,
            fade_in=2.0,
            fade_out=2.0,
            description=f"[MOCK] {genre} background music - {music_mood} mood"
        )

    async def _design_sound_effects(
        self,
        clips: List[SceneClip],
        audio_direction: Dict[str, Any]
    ) -> List[AudioLayer]:
        """
        Add sound effects at key moments
        """
        sfx_layers = []
        sfx_moments = audio_direction.get('sfx_moments', [])

        cumulative_time = 0
        for clip in clips:
            # Check if this scene has SFX
            for sfx in sfx_moments:
                if sfx.get('scene') == clip.sequence_number:
                    effect_type = sfx.get('effect', 'whoosh')
                    timing = sfx.get('timing', 0)
                    reason = sfx.get('reason', '')

                    # Get SFX from library
                    sfx_url = self._get_sfx_from_library(effect_type)

                    sfx_layers.append(AudioLayer(
                        layer_type="sfx",
                        audio_url=sfx_url,
                        start_time=cumulative_time + timing,
                        duration=0.5,  # Most SFX are short
                        volume=audio_direction.get('volume_mix', {}).get('sfx', 0.6),
                        description=f"{effect_type} - {reason}"
                    ))

            cumulative_time += clip.duration

        print(f"   ✅ Added {len(sfx_layers)} sound effects")
        return sfx_layers

    async def _design_ambient_audio(
        self,
        job: ProductionJob,
        audio_direction: Dict[str, Any]
    ) -> List[AudioLayer]:
        """
        Add ambient background sounds if needed
        """
        ambient_sound = audio_direction.get('ambient_sound')

        if not ambient_sound or ambient_sound == "null":
            return []

        # Create ambient layer
        ambient_layer = AudioLayer(
            layer_type="ambient",
            audio_url="https://example.com/ambient/placeholder.mp3",
            start_time=0,
            duration=job.duration_target,
            volume=audio_direction.get('volume_mix', {}).get('ambient', 0.2),
            fade_in=3.0,
            fade_out=3.0,
            description=f"Ambient: {ambient_sound}"
        )

        print(f"   ✅ Added ambient atmosphere: {ambient_sound}")
        return [ambient_layer]

    def _plan_narration_layers(self, clips: List[SceneClip]) -> List[AudioLayer]:
        """
        Create audio layer specs for narration (already generated by Audio Agent)
        """
        narration_layers = []
        cumulative_time = 0

        for clip in clips:
            if clip.audio_url:  # If Audio Agent already generated narration
                narration_layers.append(AudioLayer(
                    layer_type="narration",
                    audio_url=clip.audio_url,
                    start_time=cumulative_time,
                    duration=clip.duration,
                    volume=1.0,  # Narration is always full volume
                    description=f"Narration for scene {clip.sequence_number}"
                ))

            cumulative_time += clip.duration

        return narration_layers

    def _create_mix_specifications(
        self,
        audio_layers: List[AudioLayer],
        job: ProductionJob
    ) -> Dict[str, Any]:
        """
        Create final mixing specifications for Assembly Agent
        """
        return {
            "total_duration": job.duration_target,
            "sample_rate": 48000,  # Professional standard
            "channels": 2,  # Stereo
            "bitrate": 192,  # kbps
            "format": "aac",
            "normalization": "peak",  # Peak normalization to -1dB
            "compression": {
                "enabled": True,
                "threshold": -20,  # dB
                "ratio": 3.0,
                "attack": 5,  # ms
                "release": 50  # ms
            },
            "eq": {
                "narration_boost": "+2dB at 3kHz",  # Clarity
                "music_roll_off": "-3dB at 8kHz"   # Don't compete with narration
            },
            "ducking": {
                "music_under_narration": -6,  # Lower music by 6dB when narration plays
                "auto_duck": True
            }
        }

    def _get_sfx_from_library(self, effect_type: str) -> str:
        """
        Get sound effect URL from library
        """
        sfx = self.sfx_library.get(effect_type, {})
        return sfx.get('url', 'https://example.com/sfx/placeholder.mp3')

    def _load_sfx_library(self) -> Dict[str, Dict]:
        """
        Load sound effects library
        In production, this would be a real SFX library API
        """
        return {
            "whoosh": {
                "url": "https://example.com/sfx/whoosh.mp3",
                "duration": 0.5,
                "category": "transition"
            },
            "impact": {
                "url": "https://example.com/sfx/impact.mp3",
                "duration": 0.3,
                "category": "emphasis"
            },
            "pop": {
                "url": "https://example.com/sfx/pop.mp3",
                "duration": 0.2,
                "category": "ui"
            },
            "swoosh": {
                "url": "https://example.com/sfx/swoosh.mp3",
                "duration": 0.4,
                "category": "transition"
            },
            "rise": {
                "url": "https://example.com/sfx/rise.mp3",
                "duration": 1.0,
                "category": "build"
            },
            "hit": {
                "url": "https://example.com/sfx/hit.mp3",
                "duration": 0.3,
                "category": "emphasis"
            },
            "glitch": {
                "url": "https://example.com/sfx/glitch.mp3",
                "duration": 0.2,
                "category": "effect"
            },
            "ambient_city": {
                "url": "https://example.com/sfx/ambient_city.mp3",
                "duration": 30,
                "category": "ambient"
            },
            "ambient_nature": {
                "url": "https://example.com/sfx/ambient_nature.mp3",
                "duration": 30,
                "category": "ambient"
            }
        }

    def _get_default_audio_direction(self, job: ProductionJob) -> Dict[str, Any]:
        """Fallback audio direction when LLM not available"""
        return {
            "music_mood": "engaging",
            "energy_level": 6,
            "genre": "cinematic",
            "sfx_moments": [],
            "ambient_sound": None,
            "music_transitions": [],
            "volume_mix": {
                "narration": 1.0,
                "music": 0.3,
                "sfx": 0.6,
                "ambient": 0.2
            }
        }
